"""
Cost-Sensitive Threshold Optimisation and Precision-Recall Analysis Module.

Implements decision threshold optimisation under asymmetric business costs:
- Cost of False Negative (Missed Fraud): ₹100
- Cost of False Positive (False Alert to Fraud Analyst): ₹1

Finds the decision threshold that minimizes operational business cost rather
than simply maximizing statistical F1 score, and visualizes the PR curve.
"""

from pathlib import Path
from typing import Dict, Optional, Tuple, Union
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.metrics import (
    average_precision_score,
    confusion_matrix,
    f1_score,
    precision_recall_curve,
    precision_score,
    recall_score,
)

DEFAULT_COST_FN = 100.0  # Cost penalty for a missed fraud transaction
DEFAULT_COST_FP = 1.0    # Cost penalty for an unnecessary fraud alert


def compute_threshold_metrics(
    y_true: pd.Series,
    y_prob: np.ndarray,
    cost_fn: float = DEFAULT_COST_FN,
    cost_fp: float = DEFAULT_COST_FP,
    start: float = 0.01,
    stop: float = 0.99,
    step: float = 0.01,
) -> pd.DataFrame:
    """
    Sweep across decision thresholds and calculate business cost + classification metrics.

    Args:
        y_true: Ground truth binary labels.
        y_prob: Predicted fraud probabilities.
        cost_fn: Business cost of a False Negative (missed fraud).
        cost_fp: Business cost of a False Positive (false alert).
        start: Starting threshold in sweep.
        stop: Ending threshold in sweep.
        step: Step size for sweep.

    Returns:
        pd.DataFrame containing metrics and operational cost per threshold.
    """
    thresholds = np.arange(start, stop + step / 2, step)
    records = []
    n_samples = len(y_true)

    for t in thresholds:
        t_rounded = round(float(t), 2)
        preds = (y_prob >= t_rounded).astype(int)
        tn, fp, fn, tp = confusion_matrix(y_true, preds).ravel()

        precision_val = precision_score(y_true, preds, zero_division=0)
        recall_val = recall_score(y_true, preds, zero_division=0)
        f1_val = f1_score(y_true, preds, zero_division=0)
        total_cost = fn * cost_fn + fp * cost_fp

        records.append({
            "threshold": t_rounded,
            "precision": round(float(precision_val), 4),
            "recall": round(float(recall_val), 4),
            "f1_score": round(float(f1_val), 4),
            "total_cost": int(total_cost),
            "cost_per_1000": round(float(total_cost / n_samples * 1000), 2),
            "tp_count": int(tp),
            "fp_count": int(fp),
            "fn_count": int(fn),
            "tn_count": int(tn),
        })

    return pd.DataFrame(records)


def find_optimal_thresholds(
    cost_df: pd.DataFrame,
) -> Tuple[float, float, pd.Series, pd.Series]:
    """
    Identify both cost-minimizing and F1-maximizing decision thresholds.

    Args:
        cost_df: DataFrame generated by compute_threshold_metrics.

    Returns:
        Tuple of (cost_optimal_threshold, f1_optimal_threshold, cost_optimal_row, f1_optimal_row).
    """
    cost_opt_idx = cost_df["total_cost"].idxmin()
    f1_opt_idx = cost_df["f1_score"].idxmax()

    cost_opt_row = cost_df.loc[cost_opt_idx]
    f1_opt_row = cost_df.loc[f1_opt_idx]

    return (
        float(cost_opt_row["threshold"]),
        float(f1_opt_row["threshold"]),
        cost_opt_row,
        f1_opt_row,
    )


def compute_pr_curve_dataframe(
    y_true: pd.Series,
    y_prob: np.ndarray,
) -> pd.DataFrame:
    """
    Generate precision-recall curve coordinates for export and dashboard visualization.

    Args:
        y_true: Ground truth binary labels.
        y_prob: Predicted fraud probabilities.

    Returns:
        pd.DataFrame with 'threshold', 'precision', and 'recall' columns.
    """
    precisions, recalls, thresholds = precision_recall_curve(y_true, y_prob)

    pr_curve_df = pd.DataFrame({
        "threshold": np.append(thresholds, 1.0),
        "precision": precisions[:-1].tolist() + [precisions[-1]],
        "recall": recalls[:-1].tolist() + [recalls[-1]],
    })
    return pr_curve_df


def plot_and_save_pr_cost_curves(
    y_true: pd.Series,
    y_prob: np.ndarray,
    cost_df: pd.DataFrame,
    optimal_threshold: float,
    f1_optimal_threshold: Optional[float] = None,
    output_path: Union[str, Path] = "docs/pr_curve_annotated.png",
    model_name: str = "Stacked Ensemble",
) -> None:
    """
    Generate dual-panel diagnostic chart:
    Panel 1: Precision-Recall Curve with baseline and operating point.
    Panel 2: Cost per 1,000 Transactions vs Threshold with F1 overlay.

    Args:
        y_true: Ground truth binary labels.
        y_prob: Predicted probabilities.
        cost_df: DataFrame with cost and metric sweep.
        optimal_threshold: Selected operating threshold.
        f1_optimal_threshold: Comparison F1 threshold.
        output_path: Filepath where the resulting figure is saved.
        model_name: Model title string for legend.
    """
    precisions, recalls, pr_thresholds = precision_recall_curve(y_true, y_prob)
    pr_auc = average_precision_score(y_true, y_prob)

    if len(pr_thresholds) > 0:
        opt_idx = np.argmin(np.abs(pr_thresholds - optimal_threshold))
        opt_precision = precisions[opt_idx]
        opt_recall = recalls[opt_idx]
    else:
        opt_precision = precisions[0]
        opt_recall = recalls[0]

    fig, axes = plt.subplots(1, 2, figsize=(16, 6))
    fig.suptitle("Credit Card Fraud Detection — Model Performance", fontsize=14, fontweight="bold")

    # --- Left Subplot: Precision-Recall Curve ---
    axes[0].plot(
        recalls, precisions,
        color="#2563eb",
        linewidth=2,
        label=f"{model_name} (PR-AUC = {pr_auc:.4f})",
    )
    axes[0].fill_between(recalls, precisions, alpha=0.10, color="#2563eb")

    axes[0].scatter(
        opt_recall, opt_precision,
        color="#dc2626", s=150, zorder=5,
        label=f"Optimal threshold = {optimal_threshold:.2f}\n(Precision={opt_precision:.3f}, Recall={opt_recall:.3f})",
    )

    baseline = float(y_true.mean())
    axes[0].axhline(
        y=baseline,
        color="gray", linestyle="--", alpha=0.7,
        label=f"Random baseline ({baseline:.4f})",
    )

    axes[0].set_xlabel("Recall", fontsize=12)
    axes[0].set_ylabel("Precision", fontsize=12)
    axes[0].set_title("Precision-Recall Curve\n(Annotated with Optimal Business Threshold)", fontsize=11)
    axes[0].legend(fontsize=9)
    axes[0].grid(alpha=0.3)
    axes[0].set_xlim([0, 1])
    axes[0].set_ylim([0, 1.05])

    # --- Right Subplot: Business Cost vs Threshold ---
    axes[1].plot(
        cost_df["threshold"], cost_df["cost_per_1000"],
        color="#dc2626", linewidth=2,
        label="Business Cost per 1000 tx",
    )
    axes[1].axvline(
        x=optimal_threshold,
        color="#16a34a", linestyle="--", linewidth=2,
        label=f"Cost-optimal threshold = {optimal_threshold:.2f}",
    )

    if f1_optimal_threshold is not None:
        axes[1].axvline(
            x=f1_optimal_threshold,
            color="#7c3aed", linestyle=":", linewidth=2,
            label=f"F1-optimal threshold = {f1_optimal_threshold:.2f}",
        )

    axes[1].fill_between(
        cost_df["threshold"], cost_df["cost_per_1000"],
        alpha=0.10, color="#dc2626",
    )

    ax2 = axes[1].twinx()
    ax2.plot(
        cost_df["threshold"], cost_df["f1_score"],
        color="#7c3aed", linewidth=1.5, linestyle=":",
        alpha=0.9, label="F1 Score",
    )
    ax2.set_ylabel("F1 Score", color="#7c3aed", fontsize=11)
    ax2.tick_params(axis="y", labelcolor="#7c3aed")

    axes[1].set_xlabel("Decision Threshold", fontsize=12)
    axes[1].set_ylabel("Estimated Cost per 1000 Transactions (₹)", fontsize=11)
    axes[1].set_title("Business Cost vs Threshold\n(Cost-optimal vs F1-optimal)", fontsize=11)
    axes[1].grid(alpha=0.3)

    lines1, labels1 = axes[1].get_legend_handles_labels()
    lines2, labels2 = ax2.get_legend_handles_labels()
    axes[1].legend(lines1 + lines2, labels1 + labels2, loc="upper left", fontsize=9)

    plt.tight_layout()

    out_file = Path(output_path)
    out_file.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(out_file, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"Annotated PR and cost curves saved to '{out_file.resolve()}'")
